version: '2'
services:
  db:
    image: postgres
  web:
    image: railsweb:v1
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USER_NAME=postgres
      - DATABASE_PASSWORD=
    depends_on:
      - db